vim.opt.number         = true
vim.opt.relativenumber = true
vim.opt.termguicolors  = true
vim.opt.wrap           = false
vim.opt.tabstop        = 4
vim.opt.shiftwidth     = 4
vim.opt.expandtab      = true
vim.opt.smarttab       = true
vim.opt.scrolloff      = 8
vim.opt.cursorline     = true
vim.opt.clipboard      = "unnamedplus"
vim.g.mapleader        = " "
vim.opt.hlsearch       = false
vim.opt.incsearch      = true
vim.opt.colorcolumn    = "120"
vim.opt.ignorecase     = true
vim.opt.smartcase      = true
vim.opt.splitright      = true
vim.cmd("colorscheme kanagawa")
